# Generated by Django 5.1.6 on 2025-02-24 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
